name: Luacheck

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:

  luacheck:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Luacheck
        uses: lunarmodules/luacheck@v1
