name: "Test nix unstable"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v22
    - run: nix profile install nixpkgs#nix-prefetch-git
    - run: nix profile install .
    # - run: result/bin/luarocks nix lua-iconv
    - run: result/bin/luarocks nix std.normalize
    - run: result/bin/luarocks nix lua-iconv
    - run: result/bin/luarocks nix cqueues
    - run: result/bin/luarocks nix digestif
    - run: result/bin/luarocks nix https://github.com/luarocks/argparse.git
