name: "Test nix unstable"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Test on various luarocks packages

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v26
    - run: nix profile install nixpkgs#nix-prefetch-git
    - run: nix profile install .
    - name: On std.normalize
      run: nix run . -- nix std.normalize
      if: always()
    - run: nix run . -- nix lua-iconv
      if: always()
    - run: nix run . -- nix cqueues
      if: always()
    - run: nix run . -- nix digestif
      if: always()
    - run: nix run . -- nix https://github.com/luarocks/argparse.git
      if: always()
