name: "Test nix unstable"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v22
    - run: nix build
    - run: result/bin/luarocks nix lua-iconv
